/** @type {import('tailwindcss').Config} */
export default {
  important: false,
  content: [
    './src/**/*.{jsx,js,ts,tsx}',
    './index.html',
  ],
  theme: {
    extend: {
      colors: {
        espresso: 'var(--color-espresso)',
        'espresso-dark': 'var(--color-espresso-dark)',
        coffee: 'var(--color-coffee)',
        'coffee-light': 'var(--color-coffee-light)',
        gold: 'var(--color-gold)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        'soft-green': 'var(--color-soft-green)',
        cream: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        card: 'var(--color-card)',
        white: 'var(--color-white)',
        footer: 'var(--color-footer)',
      },
      fontFamily: {
        serif: ['var(--font-serif)', 'serif'],
        sans: ['var(--font-sans)', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        eyebrow: 'var(--fs-eyebrow)',
        micro: 'var(--fs-micro)',
        label: 'var(--fs-label)',
        'btn-sm': 'var(--fs-btn-sm)',
        small: 'var(--fs-small)',
        text: 'var(--fs-text)',
        lead: 'var(--fs-lead)',
        btn: 'var(--fs-btn)',
        body: 'var(--fs-body-sm)',
        section: 'var(--fs-section)',
        h1: 'var(--fs-h1)',
        h2: 'var(--fs-h2)',
        h3: 'var(--fs-h3)',
      },
      fontWeight: {
        regular: 'var(--fw-regular)',
        medium: 'var(--fw-medium)',
        semibold: 'var(--fw-semibold)',
        bold: 'var(--fw-bold)',
      },
      lineHeight: {
        tight: 'var(--lh-heading)',
        'tight-sm': 'var(--lh-heading-sm)',
        body: 'var(--lh-body)',
        text: 'var(--lh-text)',
        small: 'var(--lh-small)',
        lead: 'var(--lh-lead)',
        ui: 'var(--lh-ui)',
      },
      letterSpacing: {
        tight: 'var(--tracking-tight)',
        btn: 'var(--tracking-btn)',
        eyebrow: 'var(--tracking-eyebrow)',
        label: 'var(--tracking-label)',
        wide: 'var(--tracking-wide)',
        tagline: 'var(--tracking-tagline)',
      },
      duration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
        enter: 'var(--duration-enter)',
      },
      ease: {
        default: 'var(--ease)',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        card: 'var(--shadow-card)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        preloader: 'var(--z-preloader)',
      },
      spacing: {
        section: 'var(--section-pad-desktop)',
        'section-mobile': 'var(--section-pad-mobile)',
      },
      radius: {
        btn: 'var(--radius-btn)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        soft: 'var(--radius-soft)',
      },
      maxWidth: {
        container: 'var(--container-max)',
        content: 'var(--content-max)',
      },
      inset: {
        x: 'var(--gutter)',
      },
      padding: {
        x: 'var(--gutter)',
      },
    },
  },
  plugins: [],
}
