export { createContactMessage } from './contact'
export { toMenuItem, toMenuItems, toCafeCards } from './menuItem'
export { toGalleryImage, toGalleryImageList } from './galleryImage'
export { homePageData } from './home'
export { storyPageData } from './story'
export { menuPageData } from './menu'
export { galleryPageData } from './gallery'
export { visitPageData } from './visit'
export { toLegalDocument } from './legal'
export { notFoundPageData } from './not-found'